FROM osrf/ros:noetic-desktop-full

ENV QT_DEBUG_PLUGINS=1

RUN apt-get update
RUN apt-get install -y git
RUN git config --global user.name "weifu-yee"
RUN git config --global user.email "chenweifu9999@gmail.com"

RUN apt-get install -y python3-pip
RUN sudo apt install libopencv-dev python3-opencv

RUN sudo apt-get install ros-noetic-rosserial-msgs

RUN apt-get install -y libqt5gui5

# RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc
# RUN echo "source /root/tdk_ws/devel/setup.bash" >> /root/.bashrc

RUN echo "ALL DONE !"